version: '3.8'
services:
  alias:
    build:
      context: .
      dockerfile: dockerfile #ensure your Dockerfile is named Dockerfile, if not change this line.
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped